---
knit: "bookdown::preview_chapter"
---

# Events

The format for listing an R event is

  * Date: [event name & link](http://www.example.com). Town, Country. Social Media Link.

## 2026 `r get_btn()` {-}

### September
  * September 14-16: Posit::conf(2026). Houston, USA.

### August
  * August: 10-12: [Bioc2026](https://bioc2026.bioconductor.org/). Seattle, USA.

### July
  * July 6-9: UseR! 2026. Warsaw, Poland.
  * July 9-10: Ghana R Conference 2026. Accra, Ghana

### June
  * June 4-5: [AI in Production](https://ai-in-production.jumpingrivers.com/). Newcastle, UK.

### May
  * May 4-8: [R/Medicine 2026](https://rconsortium.github.io/RMedicine_website/), Virtual.

### February
  * February 18-19: [R!sk 2026](https://rconsortium.github.io/Risk_website/cfp.html), Virtual.
  * February 25-26: [rainbowR conference](https://conference.rainbowr.org), Virtual.

## 2025 `r get_btn()` {-}

### December
  * December 1-5: [LatinR](https://latinr.org/en/), Vitural. [\@latinrconf.bsky.social](https://bsky.app/profile/did:plc:5u5rzl53uyllkq7swmjfa32s).
  * December 6: [Japan.R 2025](https://japanr.connpass.com/event/374714/). Tokyo, Japan.

### November
  * November 3-7: [R/Pharma Virtual Conference](https://rinpharma.com/docs/RPH2025/)
  * November 12-13: [R+AI](https://r-consortium.org/posts/r_plus_ai_call_for_proposals/)
  * November 13-14: [NHS RPySOC 2025](https://nhsrcommunity.com/conference.html) London, UK and online [\@NHS-R Community](https://bsky.app/profile/nhsrcommunity.bsky.social)

### October
  * October 14-16: [EARL](https://earl-conference.com/). Brighton, UK.
  * October 8-9: [Shiny in Production](https://shiny-in-production.jumpingrivers.com/). Newcastle upon Tyne, UK. [\@jumping_uk](https://bsky.app/profile/jumpingrivers.com).

### September
  * September 16-18: [posit::conf](https://posit.co/). Atlanta, GA, USA.  [\@posit_pbc](https://twitter.com/posit_pbc).

### August
  * August 8-10: [useR](https://user2025.r-project.org/). Durham, North Carolina, USA.
  * August 19: [GenAI in Pharma](https://rinpharma.com/post/2025-06-14-announcement/)

### June
  * June 10-13: [R Medicine](https://rconsortium.github.io/RMedicine_website/). Virtual.
  * June 19-20: [Ghana R Conference](https://ghana-rusers.org/)
  * June 20-21: [CCascadia R Conference](https://cascadiarconf.com/cfp/). Portland, OR, USA.

### May
 * May 19-21: [Rencontres R 2025](https://rr2025.sciencesconf.org/). Mons, Belgium.

### April
  * April 9-11: [ShinyConf2025](https://events.ringcentral.com/events/shinyconf-2025). Virtual. [\@ShinyConf](https://x.com/ShinyConf)
  * April 11-12th: [Open Source Quantitative Finance conference (osQF, formerly R/Finance)](https://www.osqf.org/). Chicago, USA.

## 2024 `r get_btn()` {-}

### December
  * December 7: [Japan.R 2024](https://japanr.connpass.com/event/334154/). Tokyo, Japan.

### November

  * November 6-8: [III Congreso & XIV Jornadas de Usuarios de R](https://www.imus.us.es/congresos/IIIRqueR/). Sevilla, Spain.
  * November 20-22: [LatinR 2024 | Conferencia Latinoamericana sobre Uso de R en I+D](https://www.eventbrite.cl/e/latinr-2024-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-970622687587?aff=oddtdtcreator). Virtual. [\@LatinR_Conf](https://x.com/latinr_conf?lang=en).
  * November 21-22: [NHS-R / NHS.Pycom Open Source Conference (NHS RPySOC 2024)](https://nhsrcommunity.com/events/#event_type-conferences). Birmingham, UK. [\@NHSrCommunity\@fosstodon.org](https://fosstodon.org/@NHSrCommunity)
  * November 27-29: [uRosConf](https://r-project.ro/conference2024.html). Athens, Greece. [\@uRosconf](https://twitter.com/uRosconf)

### October

  * October 9-10: [Shiny in Production 2024](https://shiny-in-production.jumpingrivers.com/). Newcastle upon Tyne, UK. [\@jumping_uk](https://twitter.com/jumping_uk).
  * October 29-31: [R/Pharma Conference 2024](https://rinpharma.com/). Virtual. [\@rinpharma](https://x.com/rinpharma)

### September

  * September 4-5: [EARL 2024](https://datacove.co.uk/earl-2024-tech-conference/). Brighton, UK. [\@Datacove1](https://twitter.com/Datacove1)

### August

  * August 12-14: [posit::conf](https://posit.co/). Seattle, WA, USA.  [\@posit_pbc](https://twitter.com/posit_pbc).

### July

  * July 8-11: [useR! 2024](https://www.r-project.org/conferences/). Salzburg, Austria. [\@_useRconf](https://twitter.com/_useRconf).
  * July 24-26: [Bioconductor Conference](https://www.bioc2024.bioconductor.org/). Grand Rapids, MI, USA. [\@Bioconductor](https://twitter.com/Bioconductor).

### June

  * June 5-6: [D4 Conference](https://d4con.io/). Tampa, FL, USA. [\@d4conio](https://twitter.com/d4conio).
  * June 10-14: [R/Medicine 2024](https://rconsortium.github.io/RMedicine_website/). Virtual. [\@r_medicine](https://twitter.com/r_medicine).
  * June 12-14: [Rencontres R 2024](https://rr2024.sciencesconf.org/). Vannes, France. [\@rencontres_R](https://twitter.com/rencontres_r).
  * June 21-22: [Cascadia R Conf](https://cascadiarconf.com/). Seattle, WA, USA. [\@cascadiarconf](https://twitter.com/cascadiarconf).

### May

  * May 15-17: [New York R Conference](https://rstats.ai/). New York, NY, USA. [\@rstatsai](https://twitter.com/rstatsai)
  * May 17-18: [R/Finance 2024](https://www.rinfinance.com/). Chicago, IL, USA.

### April

  * April 17-19: [ShinyConf 2024](https://www.shinyconf.com/). Virtual. [\@ShinyConf](https://twitter.com/ShinyConf).
  * April 27: [SatRdays London 2024](https://satrday-london-2024.jumpingrivers.com/). London, UK.

## 2023 `r get_btn()` {-}

### October

  * October 12-13: [Shiny in Production 2023](https://shiny-in-production.jumpingrivers.com/). Newcastle upon Tyne, UK. [\@jumping_uk](https://twitter.com/jumping_uk).

### September

  * September 17-20: [posit::conf(2023)](https://posit.co/conference/). Chicago, IL, USA. [\@posit_pbc](https://twitter.com/posit_pbc).

### August

  * August 2-4: [BioC2023](http://bioconductor.org/). Boston, MA, USA. [\@Bioconductor](https://twitter.com/Bioconductor).
  * August 19: [Cascadia R Conf](https://cascadiarconf.org/cfp/). Seattle, WA, USA. [\@cascadiarconf](http://twitter.com/cascadiarconf).

### June

  * June 6-9: [R / Medicine](https://events.linuxfoundation.org/r-medicine/). [\@r_medicine](https://twitter.com/r_medicine).
  * June 9: [R for Health Technology Assessment (HTA) workshop](https://r-hta.org/events/workshop/2023/). York, UK. **Note**: This is part of a larger online event (see virtual events section).
  * June 8-12: [R for Health Technology Assessment (HTA) workshop](https://r-hta.org/events/workshop/2023/).
  * June 21-23: [Rencontres R 2023](https://twitter.com/rencontres_r). Avignon, France. [\@rencontres_R](https://twitter.com/rencontres_r).

### May

  * May 9-20: [R / Finance](https://www.rinfinance.com/). Chicago, IL, USA.

### April

  * April 22: [SatRdays London 2023](https://satrday-london-2023.jumpingrivers.com/). London, UK.

### March

  * March 15-17: [ShinyConf 2023](https://shinyconf.com/). [\@ShinyConf](https://twitter.com/ShinyConf).

## 2022 `r get_btn()` {-}

### December

  * December 1-2: [2022 Government & Public Sector R Conference](https://rstats.ai/gov/). Washington DC, USA.
  * December 26-30: [IISA](intindstat.org/conference2022/index). Bengaluru, India.

### November

  * November 8-10: [R/Pharma](https://rinpharma.com/).
  * November 26-27: [R confeRence](https://www.r-conference.com/).

### October

* October 6-7: [Shiny in Production](https://shiny-in-production.jumpingrivers.com/). Newcastle upon Tyne, UK. [\@jumping_uk](https://twitter.com/jumping_uk)

### September

* September 6-8: [EARL 2022](https://info.mango-solutions.com/earl-conference-2022). London, United Kingdom. [\@earlconf](https://twitter.com/earlconf)
* September 14-16: [EUROBIOC 2022](https://eurobioc2022.bioconductor.org/). Heidelberg, Germany. [\@Bioconductor](https://twitter.com/Bioconductor)

### August

  * August 6-11: [JSM](https://ww2.amstat.org/meetings/jsm/2022/conferenceinfo.cfm). Washington DC, USA. [\@AmstatNews](https://twitter.com/AmstatNews)
  * August 23-26: [R/Medicine](https://events.linuxfoundation.org/r-medicine/). [\@r_medicine](https://twitter.com/r_medicine)

### July

  * July 25-28: [rstudio::conf 2022](https://www.rstudio.com/conference/). Washington DC, USA. [\@rstudio](https://twitter.com/rstudio)
  * July 27-29: [BioC 2022](https://bioc2022.bioconductor.org/). Seattle WA, USA. [\@Bioconductor](https://twitter.com/Bioconductor)

### June

  * June 3-4: [R/Finance](https://web.cvent.com/event/2efa4ed6-5d94-44cf-9c15-e0ae8d78276e/summary?environment=P2). Chicago IL, USA.
  * June 7-10: [Symposium on Data Science and Statistics](https://ww2.amstat.org/meetings/sdss/2022/index.cfm). Pittsburgh PA, USA. [\@AmstatNews](https://twitter.com/AmstatNews)
  * June 8-10: [R Conference](https://rstats.ai/nyr/). New York NY, USA. [\@rstatsai](https://twitter.com/rstatsai)
  * June 15-17: [Insurance Data Science Conference](https://insurancedatascience.org/). Milan, Spain.
  * June 20-23: [useR!](https://user2022.r-project.org/). [\@_useRconf](https://twitter.com/_useRconf)

### March

  * March 14-15: [Workshop on Parallel Computing in R](https://warwick.ac.uk/research/rtp/sc/sulis/events/parallelr/).

## 2021 `r get_btn()` {-}

### December

  * December 10: [Why R? 2021](http://2021.whyr.pl/). [\@whyRconf](https://twitter.com/whyrconf)

### November

  * November 1-5 & 8-10: [NHS-R Community Conference 2021](https://nhsrcommunity.com/nhs-r-community-conference-2021/). [\@NHSrCommunity](https://twitter.com/NHSrCommunity)
  * November 8-13: [Coda BR 2021](https://escoladedados.org/coda2021/).
  * November 10-12: [LatinR 2021](https://latin-r.com/en). [\@latinr_conf](https://twitter.com/latinr_conf)
  * November 19: [Korea R Conference](https://use-r.kr/)
  * November 24-26: [The Use of R in Official Statistics](https://r-project.ro/conference2021.html)

### September

  * September 6-10: [Earl 20201](https://info.mango-solutions.com/earl-2021).
  * September 29-30: [noRth 2021](https://rnorthconference.github.io/).

### August

   * August 4-6: [BioC2021](https://bioc2021.bioconductor.org/).
   * August 24-27: [R Medicine](https://events.linuxfoundation.org/r-medicine/). [\@r_medicine](https://twitter.com/r_medicine).

### July

  * July 6-9: [useR 20201](https://user2021.r-project.org/).

### June

  * June 4-5: [CascadiaRConf](https://cascadiarconf.com/). [\@cascadiarconf](https://twitter.com/cascadiarconf)
  * June 17: [R Lille Meetup](https://www.meetup.com/R-Lille/events/277902715/). [\@rlille_rug](https://twitter.com/rlille_rug)

### April

  * April 15: [R Lille Meetup](https://www.meetup.com/R-Lille/events/277031496/). [\@rlille_rug](https://twitter.com/rlille_rug).
  * April 16-18: [WhyR? Turkey 2021](http://whyr.pl/2021/turkey/)
  * April 29: [R Lille Meetup](https://www.meetup.com/R-Lille/events/277132394/). [\@rlille_rug](https://twitter.com/rlille_rug).

### January

  * January 21: [RStudio Global](https://rstudio.com/conference/).
  * January: [Evidence Synthesis & Meta-Analysis in R](https://www.eshackathon.org/events/2021-01-ESMAR.html). [\@eshackathon](https://twitter.com/eshackathon)

## 2020 `r get_btn()` {-}

### December

  * December 2-4: The Use of R in Official Statistics - [uRos2020](http://r-project.ro/conference2020.html#keynote_speakers). Vienna, Austria.
  * December 2-4: [The R Conference | Government & Public Sector](https://rstats.ai/gov/). [#rstatsdc](https://twitter.com/search?q=%23rstatsdc&src=typed_query).

### November

  * November 14: [SatRday Columbus](https://columbus2020.satrdays.org/). [#satRdayColumbus](https://twitter.com/search?q=%23satRdayColumbus&src=typed_query).

### October

  * October 12-16: [R in Pharma](https://rinpharma.com/).
  * October 7-9: [LatinR 2020](https://github.com/LatinR/presentaciones-LatinR2020). [\@latinr_conf](https://twitter.com/latinr_conf)

### September

  * September 24-27: [Why R](https://2020.whyr.pl/)

### August

  * August 12-15: [New York R Conference](https://rstats.ai/nyr/)
  * August 27-30: [R in Medicine](https://events.linuxfoundation.org/r-medicine/).

### July

  * July 7-10: [useR! 2020](https://user2020.r-project.org/). [\@useR2020stl](https://twitter.com/useR2020stl).
  * July 7-10: [useR! 2020 European Hub](https://user2020muc.r-project.org/). [\@useR2020muc](https://twitter.com/useR2020muc).
  * July 14-15: [noRth 2020](https://rnorthconference.github.io/).
  * July 23: [Newcastle Data Science Meet-up](https://www.meetup.com/Newcastle-Upon-Tyne-Data-Science-Meetup/events/271494400/).

### June

  * June 17-22: [eRum 2020](http://2020.erum.io/). [\@erum2020_conf](https://twitter.com/erum2020_conf).
  * June 23: [LondonR](https://mango-solutions.zoom.us/meeting/register/tJAtfuGsqjgiHtCTMIp4hgGHQTvfK8kD1kiU).
  * June 28: [BristolR](https://www.meetup.com/Bristol-R-User-Group/events/271309225/).

### May

  * May 30: [SatRday Chicago](https://chicago2020.satrdays.org).

### April

 * April 17: [Women+ Data Science \@MSU](https://women-plus-datascience.github.io/home). East Lansing, MI, USA.

### March

  * March 7: [SatRdays Johannesburg](https://joburg2020.satrdays.org/). Johannesburg, South Africa.
  * March 14: [SatRday Neuchâtel](https://neuchatel2020.satrdays.org/). Neuchâtel, Switzerland.
  * March 14-15: [Chicago R Collaborative](https://chircollab.github.io/). Chicago, USA. [#chircollab](https://twitter.com/search?q=%23chircollab)

### February

 * February 1: [SatRdays Abidjan](https://abidjan2020.satrdays.org/). Abidjan, Côte d'Ivoire.
 * February 22: [SatRdays Auckland](https://auckland2020.satrdays.org/). Auckland, New Zealand.
 * February 28-29: [CelebRation 2020](http://www.celebration2020.org/). Copenhagen, Denmark.

### January

 * January 27-30: [rstudio::conf(2020)](https://www.rstudio.com/conference/). San Francisco, USA.

## 2019 `r get_btn()` {-}

### December

  * December 6-8: [Yes We CRAN](https://www.thinksisu.org/event/yeswecran/). Washington, D.C.
  * December 11-13: [rOpenSci OzUnconf](https://ozunconf19.ropensci.org/). Sydney, Australia.
  * December 26: [R\@IISA](https://r-iisa2019.rbind.io/). Mumbai, India.

### November

  * November 7-9: [DC R Conference](https://dc.rstats.ai/). Washington, D.C.
  * November 16: [SatRdays Cardiff](https://cardiff2019.satrdays.org/). Cardiff, UK.

### September

  * September 12-14: [R/Medicine 2019](https://r-medicine.com/). Boston MA, USA.
  * September 25-27: [LatinR 2019](http://latin-r.com/). Santiago, Chile. [\@LatinR_Conf](https://twitter.com/LatinR_Conf)
  * September 26-29: [Why R?](http://whyr.pl/2019/). Warsaw, Poland [\@whyRconf](https://twitter.com/whyRconf)

### August

 * August 15-16: [noRth 2019](https://rnorthconference.github.io/). Minneapolis MN, USA.

### July

  * July 9-12: [useR! 2019](http://www.user2019.fr/). Toulouse, France. [\@UseR2019_Conf](https://twitter.com/UseR2019_Conf)
   * July 9-12: [Riot 2019](http://riotworkshop.github.io/). Co-located with useR!
  * July 29-August 2: [CDSB Workshop 2019](https://comunidadbioinfo.github.io/post/building-tidy-tools-cdsb-runconf-2019/#.XP6i_dNKi50). Cuernavaca, Mexico.

### June

  * June 8: [Cascadia R Conference](https://cascadiarconf.com/). Redmond WA, USA.
  * June 15: [SatRday Berlin](https://berlin2019.satrdays.org/). Berlin, Germany.

### May

  * May 9-11: [New York R Conference](https://www.rstats.nyc/). New York NY, USA.
  * May 18: [1 Year Chapter Meetup Belo Horizonte](http://rladiesbh.com.br/). Belo Horizonte, Brazil.
  * May 18: [SatRday Gdansk](https://gdansk2019.satrdays.org/). Gdansk, Poland.
  * May 20-21: [The Use of R in Official Statistics](http://r-project.ro/conference2019.html). Bucharest, Romania.
  * May 25: [SatRday Kampala2019](https://kampala2019.satrdays.org/). Kampala, Uganda.

### April

  * April 6: [satRday Los Angeles](https://losangeles2019.satrdays.org/). Los Angeles CA, USA.
  * April 6: [satRday Johannesburg](https://joburg2019.satrdays.org/). Johannesburg, South Africa.
  * April 6: [satRdays Newcastle](https://newcastle2019.satrdays.org/). Newcastle, UK.
  * April 12: [Women in Data Science East Lansing \@MSU](https://github.com/rladies-eastlansing/wids2019/wiki). East Lansing, MI, USA.
  * April 14-16: [The Uncoast Unconference](https://uncoast-unconference.netlify.com/). Des Moines IA, USA.
  * April 27: [SatRday Chicago](https://chicago2019.satrdays.org/). Chicago IL, USA.

### March

  * March 9-10: [Chicago R Unconference](https://chirunconf.github.io/). Chicago IL, USA.

### February

  * February 23: [satRdays Paris](http://paris2019.satrdays.org). Paris, France.

### January

  * January 15-18: [rstudio::conf](https://www.rstudio.com/conference/). Austin, USA.
  * January 24-26: [ConectaR 2019](http://www.conectar2019.ucr.ac.cr/). San Jose, Costa Rica.

## 2018 {-}

### December

 * December 6-7: [European Bioconductor Meeting 2018](https://bioconductor.github.io/EuroBioc2018/). Munich, Germany.
 * December 8: [SatRDays DC](https://dc2018.satrdays.org/). Washington, USA.
 * December 15: [SatRday Santiago](https://santiago2018.satrdays.org). Santiago, Chile.

### November

 * November 7: [EARL Seattle](https://earlconf.com/boston). Seattle, USA. [\@earlconf](https://twitter.com/earlconf)
 * November 8-9: [DC R Conference](https://www.rstats.ai/). Washington DC, USA. [\@rstatsdc](https://twitter.com/rstatsdc)
 * November 9: [EARL Houston](https://earlconf.com/boston). Houston, USA. [\@earlconf](https://twitter.com/earlconf)
 * November 13: [EARL Boston](https://earlconf.com/boston). Boston, USA. [\@earlconf](https://twitter.com/earlconf)

### October

 * October 26: [Noreast'R Conference](http://noreastrconf.com/). Providence, USA. [\@noreastrconf](https://twitter.com/noreastrconf/)
 * October 27: [SatRday Belgrade](http://belgrade2018.satrdays.org/). Belgrade, Serbia.

### September

 * September 1: [SatRday Amsterdam](http://amsterdam2018.satrdays.org/). Amsterdam, The Netherlands.
 * September 4-5: [LatinR 2018](http://latin-r.com/). Buenos Aires, Argentina. [\@LatinR2018](https://twitter.com/latinr2018)
 * September 11-13: [EARL London 2018](https://earlconf.com/london/). London, United Kingdom. [\@earlconf](https://twitter.com/earlconf)
 * September 12-14: [The Use of R in Official Statistics](https://www.aanmelder.nl/uros2018). Hague, Netherlands. [\@uRos2018](https://twitter.com/uRos2018)

### August

 * August 15-16: [R/Pharma](http://rinpharma.com/). Massachusetts, USA.

### July

 * July 2-5: WhyR? 2018. Wroclaw, Poland.
 * July 4-6: [7eme rencontres R](https://r2018-rennes.sciencesconf.org). Rennes, France. [\@rencontres_R](https://twitter.com/rencontres_R)
 * July 10-13: [useR! 2018](https://user2018.r-project.org/). Brisbane, Australia.

### June

 *  June 1-2: [R/Finance 2018](http://www.rinfinance.com). Chicago, USA.
 *  June 2: [CascadiaRConf](https://cascadiarconf.com/). Portland, USA. [\@cascadiarconf](https://twitter.com/cascadiarconf)

### May

  * May: [The European #rstats Users Meeting](http://2018.erum.io/). Budapest, Hungary. [\@erum2018](https://twitter.com/erum2018)
  * May 22: [R Day](http://rday.leg.ufpr.br/). Curitiba, Brazil. [\@LEG_UFPR](https://twitter.com/LEG_UFPR)

### April
 * April 20-21: [New York R Conference](http://rstats.nyc/). New York, USA.

### March

  * March 17th: [SatRday](http://capetown2018.satrdays.org/). Cape Town, South Africa.

### January

  * January 31, Feb 1-3: [rstudio::conf](https://www.rstudio.com/conference/). San Diego, USA.

## 2017 {-}

### December

  * December 5-6: [Bioconductor European Conference](https://bioconductor.org/help/course-materials/2017/BioCEurope/). Cambridge, UK.

### November

  * November 1-3: [EARL Boston 2017](https://earlconf.com/boston/). Boston, USA.
  * November 6-7: New Challenges for Statistical Software - The Use of R in Official Statistics. Bucharest, Romania.
  * November 8-9: [R Kenntnis-Tage 2017](http://www.eoda.de/de/R-Kenntnis-Tage.html). Kassel, Germany.
  * November 16-17: Bioconductor Asia. Adelaide, Australia.

### September

  * September 13-15: [EARL London 2017](https://earlconf.com/london/). London, UK.

### July

  * July 4-7: [UseR! 2017](http://www.user2017.brussels/). Brussels, Belgium. [\@UseR_Brussels](https://twitter.com/UseR_Brussels) [Recordings](https://channel9.msdn.com/events/useR-international-R-User-conferences/)
    * July 5: [Riot](http://riotworkshop.github.io/). Co-located with useR! 2017.
  * July 27-28: [BioC 2017](https://www.bioconductor.org/help/course-materials/2017/BioC2017/). Boston, USA.

### June

  * June 3: [CascadiaRconf](https://cascadiarconf.com/2017). Portland, USA. [\@cascadiarconf](https://twitter.com/cascadiarconf)
  * June 5-7: EARL. San Francisco, USA.
  * June 8: [R in Insurance](https://rininsurance17.sciencesconf.org/). Paris, France.

### May

  * May 19-20: [R/Finance 2017](http://www.rinfinance.com). Chicago, USA. ([Recordings here](https://channel9.msdn.com/Events/RFinance/RFinance-2017))
  * May 25-26: [R à Québec 2017](http://raquebec.ulaval.ca/2017/). Québec, Canada.
  * May 25-26: ROpenSci Unconference. Los Angeles, USA.
  * May 28-Jun 2: WOMBAT MeDaScIn 2017. Melbourne, Australia.

### April

  * April 21-22: [New York R Conference 2017](http://www.rstats.nyc). New York, USA.

### March

  * March 4: [#ODDZurich Hackathon](http://zurich-r-user-group.github.io/hackathon.html). Zurich, Switzerland. [\@ZurichRUsers](https://twitter.com/ZurichRUsers)
  * March 24-25: [Women in Machine Learning & Data Science](http://www.wimldsdatadive.com/hackathons/2). New York, USA.

### February

  * February 16-18: [satRday](https://capetown2017.satrdays.org//). Cape Town, South Africa. [\@satRdays_org](https://twitter.com/satRdays_org)

### January

 * January 11-14: [rstudio::conf](https://www.rstudio.com/conference/). Kissmmee, USA.

## 2016 {-}

 * December: European Bioconductor Developers' Meeting. Basel, Switzerland.
 * November: [EARL Boston 2016](https://earlconf.com/boston/). Boston, USA.
 * October: [European R users meeting](http://erum.ue.poznan.pl/). Poznan, Poland.[\@erum2016](https://twitter.com/erum2016)
 * September:
  * [EARL London 2016](https://earlconf.com/london/). London, UK.
  * [The first satRday conference](http://budapest.satrdays.org). Budapest, Hungary.
 * July: [UseR! 2016](http://user2016.org/). Stanford, USA. ([Recordings here](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016))
 * May: [R/Finance 2016](http://www.rinfinance.com). Chicago, USA.
 * April: [New York R Conference 2016](http://www.rstats.nyc). New York, USA.
