## Europe

### Austria `r get_btn()`

  * Vienna: [Vienna<-R](https://www.meetup.com/ViennaR/)
  
### Belgium `r get_btn()`

  * Brussels: [RBelgium](https://www.meetup.com/RBelgium/)

### Czech Republic `r get_btn()` 

  * Prague: [R Meetup Group](https://www.meetup.com/Prague-R-Meetup-Group/)

### Denmark `r get_btn()`

  * Aarhus: [Rhus](https://www.meetup.com/Rhus-useR-group)
  * Copenhagen: [CopenhagenR](https://www.meetup.com/CopenhagenR-useR-Group/)
  
### Estonia `r get_btn()`

  * Tallinn: [Tallinn R Users Group](https://www.meetup.com/r-tallinn/) 

### Finland `r get_btn()`

  * Helsinki: [Finnish Society for Bioinformatics](http://www.bioinf.fi/)
  * Helsinki: [R User Group Finland](https://www.meetup.com/R-User-Group-Finland/)

### France `r get_btn()`

  *  Brest: [DataScience Brest](https://www.meetup.com/fr-FR/Data-Science-Brest/)
  *  Lille: [R Lille](http://meetup.rlille.fr/), [@rlille_rug](https://twitter.com/rlille_rug)
  *  Lyon: [RLyon](https://www.meetup.com/R-Lyon/)
  *  Jouy-en-Josas: [R4Ciam](http://ciam.inra.fr/r4ciam/)
  *  Montpellier: [Groupe des utilisateurs du logiciel R](http://forums.cirad.fr/logiciel-R/)
  *  Nancy: [Nancy Data Science](https://www.meetup.com/nancydatascience/)
  *  Nantes: [Meetup R Nantes](https://www.meetup.com/fr-FR/Meetup-R-Nantes/)
  *  Paris: [Semin-R](http://www.mnhn.fr/semin-r/)
  *  Paris: [State of the R](http://stateofther.github.io/)
  *  Paris: [R Addicts Paris](https://www.meetup.com/rparis/events/124508332/)
  *  Strasbourg: [StatsRbourg](https://www.meetup.com/StatsRbourg/)
  *  Toulouse: [R Toulouse](http://r-toulouse.netlify.com/), [\@RUG_Toulouse](https://twitter.com/RUG_Toulouse)
  *  Grenoble: [R in Grenoble](https://r-in-grenoble.github.io/)
  
### Germany  `r get_btn()`

  *  Berlin: [Berlin R Users Group](https://www.meetup.com/Berlin-R-Users-Group/ )
  *  Bochum: [R Users Group Bochum/Ruhr](https://user.ruhr-uni-bochum.de/); [\@useR_bochum](https://twitter.com/useR_bochum)
  *  Dresden: [R User Group Dresden](http://rusersdresden.wordpress.com/)
  *  Frankfurt am Main: [Campus useR Group Frankfurt](https://www.meetup.com/r-frankfurt/)
  *  Hamburg: [Hamburg R User Group](https://www.meetup.com/Hamburg-R-User-Group/)
  *  Hannover: [Hannover R User Group](https://www.meetup.com/de-DE/Hannover-R-User-Group/) 
  *  Kassel: [Kasseler useR Group](https://www.meetup.com/Kassel-useR-Group/)
  *  Kiel: [Kiel R User Group](https://www.meetup.com/de-DE/Kiel-R-User-Group/)
  *  Köln: [Köln R User Group](https://www.meetup.com/KoelnRUG/)
  *  Leipzig: [Leipzig R Statistical Computing](https://www.meetup.com/Leipzig-R-statistical-computing/)
  *  Mannheim/Ludwigshafen/Heidelberg: [R User Group Rhein-Neckar](https://www.meetup.com/R-User-Group-Rhein-Neckar)
  *  Marburg: [Marburg R Local User Group](http://www.r-marburg.de/)
  *  Munich: [Applied R Munich](https://www.meetup.com/Applied-R-Munich)
  *  Münster: [MünsteR (R Users Group)](https://www.meetup.com/Munster-R-Users-Group)
  *  Nürnberg: [NürnbergR](https://www.xing.com/net/ruser-nuernberg/)
  *  Wiesbaden: [Wiesbaden R Users Group](https://www.meetup.com/Wiesbaden-R-Users-Group)
  
### Greece `r get_btn()`

  * Athens: [AthensR](https://www.meetup.com/AthensR/)
  * Pátrai: [Patra's R Users Group](https://www.meetup.com/Patras-R-Users-Group)

### Hungary `r get_btn()`

  * Budapest: [BURN](https://www.meetup.com/Budapest-Users-of-R-Network)

### Ireland `r get_btn()`

  * Cork: [Cork R-Uses Group](https://www.meetup.com/Cork-Ireland-R-Users-Group/)
  * Dublin: [Dublin-R](https://www.meetup.com/DublinR/)

### Italy `r get_btn()`

  * Milan: [MilanoR](http://www.milanor.net/)
  * Padua: [Italy-RUG Rante](https://groups.google.com/group/rante)
  * Torino: [Torino R net](http://torinor.net/)

### Luxembourg `r get_btn()`

  * Luxembourg: [LuxR](https://www.meetup.com/LuxRgroup/)

### Netherlands `r get_btn()`

  * Amsterdam: [amst-R-dam](https://www.meetup.com/amst-R-dam/)
  * Enschede: [Twente R User Group](http://twenterug.wordpress.com/)
  * Groningen: [R User Group Groningen](http://richelbilderbeek.nl/RuserGroupGroningen.htm)
  * Nijmegen: [Nijmegen everRybody](https://www.meetup.com/Nijmegen-eveRybody/)

### Norway `r get_btn()`

  * Oslo: [Oslo user! Group](https://www.meetup.com/Oslo-useR-Group/)

### Poland `r get_btn()`

  * Warsaw: [SER - Warsaw R Users Group](https://www.meetup.com/Spotkania-Entuzjastow-R-Warsaw-R-Users-Group-Meetup/)
  * Poznań: [Poznań R Users](https://www.meetup.com/Poznan-R-User-Group-PAZUR/)
  * TriCity: [Trójmiejska Grupa Entuzjastów R](https://www.meetup.com/Trojmiejska-Grupa-Entuzjastow-R/)
  * Wrocław: [STWUR - Wroclaw R Users Group](https://www.meetup.com/Wroclaw-R-Users-Group/)
  * Kraków: [entuzjastów R krakowska alternatywa](https://www.meetup.com/erkakrakow/)

### Portugal `r get_btn()`

  * Braga: [R@Minho](https://www.meetup.com/R-Minho/)

### Romania `r get_btn()`

  * Bucharest: [R-omania Team](http://www.r-project.ro/our_team.html)

### Russia `r get_btn()`

  * Moscow: [rMoscow](https://www.meetup.com/rMoscow/)
  * St. Petersburg: [St. Petersburg R User Group](https://www.meetup.com/St-Petersburg-R-User-Group/)

### Serbia `r get_btn()`

  * Belgrade: [BelgradeR](https://www.meetup.com/BelgradeR/)
  
### Slovakia `r get_btn()`
  * Bratislava: [R <- Slovakia](https://www.facebook.com/groups/931707906955080/); [R <- Slovakia @ Meetup.com](https://www.meetup.com/R-Slovakia/)

### Slovenia `r get_btn()`

  * Ljubljana: [Rcoholics](https://groups.google.com/group/rkoholikiAnonymous)

### Spain `r get_btn()`

  * Barcelona: [BarcelonaR](https://www.barcelonar.org/)
  * Madrid: [Grupo de Interés Local de Madrid](http://madrid.r-es.org/)
  * Madrid: [R Hispano](http://r-es.org/)
  * Sevilla: [R users](https://sevillarusers.wordpress.com/); [\@_SevillaR](https://twitter.com/_SevillaR)
  * Valencia: [R users](https://valenciarusers.wordpress.com/)

### Sweden `r get_btn()`

  * Stockholm: [StockholmR](https://www.meetup.com/StockholmR/)

### Switzerland `r get_btn()`

  * Basel: [BaselR](http://www.baselr.org/)
  * Bern: [BernR](https://www.meetup.com/Bern-R/)
  * Geneva: [Geneve R User Group](https://www.meetup.com/Geneve-R-User-Group/); [\@GenevaRUsers](https://twitter.com/GenevaRUsers)
  * Geneva: [R Lunch / Dejeuner R](http://use-r-carlvogt.github.io/prochains-lunchs/)
  * Lucerne: [Lucerne R User Group](https://www.meetup.com/Lucerne-R-User-Group/)
  * Zurich: [Zurich R](https://www.meetup.com/Zurich-R-User-Group/) User Group

### United Kingdom `r get_btn()`

#### England {-}

  * Birmingham: [Birmingham R User Group](https://www.meetup.com/BirminghamR/); [\@BirminghamR](https://twitter.com/birminghamr)
  * Brighton: [BrightonR](https://www.eventbrite.co.uk/e/brighton-r-supported-by-silicon-brighton-tickets-83952178225)
  * Bristol: [Bristol R User Group](https://www.meetup.com/Bristol-R-User-Group/); [\@BristolR](https://twitter.com/BristolRUsers)
  * Coventry: [Warwick R User Group](http://warwick.ac.uk/wrug); [\@WarwickRUG](https://twitter.com/WarwickRUG)
  * Exeter: [Exeter](https://www.meetup.com/Exeter-R-Users-Group-Exeter-Devon-England/) R Users Group
  * Leeds: [R Users Leeds](https://r-users-leeds.netlify.com/about/); [\@r_users_leeds](https://twitter.com/r_users_leeds)
  * London: [LondonR](https://www.meetup.com/LondonR/)
  * Manchester: [ManchesterR](http://www.rmanchester.org/)
  * Newcastle: [R North East](https://rnortheast.github.io/); [\@RstatsNE](https://twitter.com/RstatsNE)
  * Nottingham: [Nottingham](https://www.meetup.com/NottinghamR-Nottingham-R-Users-Group/) R User group
  * Oxford: [R user group Oxford](https://r-oxford.github.io/); [\@rusersoxford](https://twitter.com/rusersoxford)
  * Portsmouth: Portsmouth useR groug; [\@r_portsmouth](https://twitter.com/r_portsmouth)
  * Sheffield: [SheffieldR](https://www.meetup.com/SheffieldR-Sheffield-R-Users-Group/);[\@Sheffield_R_](https://twitter.com/Sheffield_R_)

#### Northern Ireland {-}

  * Belfast: [Belfast R Users](http://brusers.tumblr.com/); [\@BelfastRUsers](https://twitter.com/BelfastRUsers)

#### Scotland {-}

  * Edinburgh: [Edinbr](http://edinbr.org); [\@edinb_r](https://twitter.com/edinb_r)
  * Glasgow: [RGlasgow](https://www.meetup.com/RGlasgow); [\@TeamRGlasgow](https://twitter.com/teamrglasgow)
  * Inverness: [InveRness](https://www.facebook.com/InveRness-R-User-Group-195100587522377/);[\@InvernessRug](https://twitter.com/InvernessRug)

#### Wales {-}

  * Cardiff: [Cardiff](https://www.meetup.com/Cardiff-R-User-Group/) R User Group
  * Swansea: [Swansea](https://sites.google.com/site/swanseauniversityrusergroup/home) University R User Group

### Turkey `r get_btn()`

  * Ankara: [Turkish Community](https://www.meetup.com/Turkish-Community-of-R/) of R
  * Eskisehir: [Eskisehir R User Group](https://www.meetup.com/tr-TR/Eskisehir-R-Users-Group-Data-Science-Society/)

### Ukraine `r get_btn()`

  * Kyiv: [Kyiv useR! Group](https://www.meetup.com/Kyiv-useR-Group/)
