## Asia

### China

  * Xiamen: [XMU-R](https://www.meetup.com/RGROUP/)

### Hong Kong

  * Hong Kong: [Hong Kong R User Group](https://www.facebook.com/groups/hkrusers/)

### India

  * Bangalore: [Bengaluru R UseR Group (BRUG)](https://www.meetup.com/BengaluRu-use-R-gRoup/)
  * Chennai: [R Users Group Chennai](https://www.meetup.com/R-Users-Group-Chennai/)
  * Mumbai: [mumbai-r-user-group](https://www.meetup.com/mumbai-r-user-group/?scroll=true)
  * Delhi: [Delhi NCR R useR Group](https://www.meetup.com/Delhi-NCR-useR-Group-R-programming-language/)
  * Hyderabad: [R Users Group Hyderabad RUGH](https://www.meetup.com/R-Users-Group-Hyderabad/)
  * New Delhi: [New Delhi UseR Group](https://www.meetup.com/New-Delhi-R-UseR-Group/)
  * Pune: [Pune R User Group](https://www.meetup.com/Pune-R-junkies-Meetup/)

### Japan

  * Chiba: [Kashiwa.R](http://www14.atwiki.jp/kashiwar/)
  * Fukuoka [Fukuoka.R](https://www.facebook.com/fukuoka.stat.R) [Events](https://fukuoka-r.connpass.com) [\@doradora09](https://twitter.com/doradora09) [\#FukuokaR](https://twitter.com/hashtag/FukuokaR?src=hash)
  * Chiba: [Kashiwa.R](http://www14.atwiki.jp/kashiwar/)
  * Hiroshima: [HiRosima.R](http://hiroshimar.connpass.com/) [HijiyamaR](https://atnd.org/events/81359)
  * Kobe: [Kobe.R](http://kobexr.doorkeeper.jp/) 
  * Nagoya: [Nagoya.R](https://atnd.org/events/78674)
  * Osaka: [Osaka.R](https://sites.google.com/site/osakarwiki/)
  * Sapporo: [SappoRo.R](http://kokucheese.com/event/index/423714/)
  * Sendai: [Events](https://sendair.connpass.com/) [\@tachyon7776](https://twitter.com/tachyon7776)  [\#Sendai_R](https://twitter.com/hashtag/Sendai_R?src=hash)  [\#SendaiR](https://twitter.com/hashtag/SendaiR?src=hash)
  * Shiga: [Shiga.R](http://atnd.org/events/5939)
  * Tokyo: [Tokyo.R](https://groups.google.com/group/r-study-tokyo)  [Events](https://tokyor.connpass.com/) [Slack](https://r-wakalang.slack.com) [\@TokyoRCommunity](https://twitter.com/TokyoRCommunity)   [\#TokyoR](https://twitter.com/hashtag/TokyoR?src=hash)
  * Tsukuba: [Tsukuba.R](https://www.meetup.com/ja-JP/TsukubaR/); [\@tsukubar](https://twitter.com/tsukubar)
  * Okinawa: [Okinawa.R](http://www.okadajp.org/RWiki/?%E6%B2%96%E7%B8%84R%E5%90%8C%E5%A5%BD%E4%BC%9A)
  * Yamaguchi: [Yamadai.R](https://atnd.org/events/37336) [\#yamadaiR](https://twitter.com/hashtag/YamadaiR?src=hash)
  * Yokohama: [Yokohama.R](https://github.com/YokohamaR/yokohama.r)
  
  * Japan: [Japan.R](http://japanr.net/) [Events](https://japanr.connpass.com) [\@gepuro](https://twitter.com/gepuro) [\#JapanR](https://twitter.com/hashtag/JapanR?src=hash)

### Macau

  * Macau: [R-Research](http://groupspaces.com/R-research/)

### Malaysia

  * Kuala Lumpur: [myRUG](https://www.meetup.com/MY-RUserGroup/)
  
  
### Nepal

  * Nepal: [R User Group Nepal](https://www.meetup.com/R-User-Group-Nepal/); [\@rugnepal](https://twitter.com/rugnepal)
  

### Pakistan

  * Lahore: [Lahore R Users Group](https://lahorerug.wordpress.com/)

### Philippines

  * Manila: [R Users Group](https://www.meetup.com/R-Users-Group-Philippines/)

### Singapore

  * Singapore: [R User Group](https://www.meetup.com/R-User-Group-SG/)

### South Korea

  * South Korea: [R Korea - Korean R Study Group](https://www.facebook.com/groups/krstudy/)
  * South Korea: [R Korea - Korean R User Group](https://www.facebook.com/groups/KoreaRUsers/)

### Sri Lanka

  * Peradeniya: [R User Group](https://groups.google.com/forum/?hl=en#!forum/r-user-group---srilanka) 
  
### Taiwan

  * Kaohsiung: [Kaohsiung R Users](https://www.facebook.com/groups/Kaohsiung.R.Users/#_=_)
  * Taipei: [Chinese Academy of R Software CARS](https://sites.google.com/site/zhonghuarruantixuehui/)
  * Taipei: [Taiwan UseR Group](https://www.meetup.com/Taiwan-useR-Group/)

### Thailand

  * Chang Mai: [Chang Mai R User Group](https://www.facebook.com/Chiang-Mai-R-362933103793288/)

### Viet Nam

  * Ha Noi: [Ha Noi R Users Group Meetup](https://www.meetup.com/Ha-Noi-R-Users-Group-Meetup/)
