---
knit: "bookdown::preview_chapter"
---

## Middle East/ Africa

### Tunisia `r get_btn()`

 * Tunis: [Tunis R User Group](https://www.meetup.com/tunis-r-user-group/)
 
### Algeria `r get_btn()`

 * Algiers: [Algerian R users](https://www.facebook.com/groups/1135595893158091/)
 
### Côte d'Ivoire `r get_btn()`

 * Abidjan: [Abidjan R users](https://www.meetup.com/Abidjan-R-users-Meetup/)
 
### Democratic Republic Of Congo `r get_btn()`

  * Kinshasa: [UseR!Kin](https://www.meetup.com/user-kin/)

### Egypt `r get_btn()`

  * Cairo: [Cairo Bioinformatics Group](https://www.meetup.com/Cairo-Bioinformatics-Group/)
  * Cairo: [Cairo R Users Group](https://www.meetup.com/Cairo-R-Users-Group/)

### Israel `r get_btn()`

  * Tel Aviv: [Israel R User Group](https://groups.google.com/group/israel-r-user-group)

### Kenya `r get_btn()`

  * Nairobi: [R Users Group Kenya RUGK](https://www.meetup.com/Nairobi-R-Users-Group/)
  
### Morocco `r get_btn()`

  * Casablanca: [Casablanca R Users Group](https://www.meetup.com/Casablanca-R-Users-Group/)

### Nigeria `r get_btn()`

  * Offa: [Offa R Users Group](https://www.meetup.com/FEDPOFA-R-Users-Group/)
  * Minna: [Niger Data Science and machine learning in R User Group](https://www.meetup.com/Minna-Data-Science-Meetup-Group/)

### Saudi Arabia `r get_btn()`

  * Riyadh: [Riyadh](https://riyadhusergroup.wordpress.com/)

### Senegal `r get_btn()`

  * Dakar: [DRUG](https://www.meetup.com/DakaR-R-User-Group/)

### South Africa `r get_btn()`

  * Cape Town: [Cape R Users Group](https://caperuser.wordpress.com/); [\@CapeRUser](https://twitter.com/CapeRUser)
  * Johannesburg: [Jo'burg R Users Group](https://www.meetup.com/Joburg-R-Users-Group)

### Tanzania `r get_btn()`

  * Dar es Salaam: [Dar es Salaam R Users Group](https://www.meetup.com/DarEs-Salaam-R-users/)

### Uganda `r get_btn()`

  * Kampala: [Kampala R Users Group](https://www.meetup.com/Kampala-R-Users-Group/)
