---
knit: "bookdown::preview_chapter"
---

## South America

### Argentina `r get_btn()`

  * Ciudad de Buenos Aires,[R en Buenos Aires](http://renbaires.github.io/); [\@renbaires](https://twitter.com/renbaires)
  * Rosario, [Grupo de Usuaries de R en Rosario](https://www.meetup.com/R-en-Rosario/)
  
### Brazil `r get_btn()`

  * Brasilia: [Brasília UseR Meetup Linguagem de Programação "R"](https://www.meetup.com/Brasilia-UseR-Meetup/)
  * Campinas: [Campinas R Users Meetup](https://www.meetup.com/Campinas-R-Users-Meetup/)
  * Ouro Preto: [Ouro Preto R Users Group](https://www.meetup.com/Grupo-de-Usuarios-de-R-em-Ouro-Preto/)
  * Porto Alegre: [RStat](https://www.meetup.com/UseRS_/)
  * São Paulo: [São Paulo R Users Group](https://www.meetup.com/useR-SP/)
  * Virtual: [R-br](http://leg.est.ufpr.br/doku.php/software:rbr)

### Chile `r get_btn()`

  * Santiago: [Grupo de Usuarios de R en Chile](https://www.meetup.com/useRchile/)

### Colombia `r get_btn()`

  * Bogota: [Bogotá R Users Group](https://www.meetup.com/it/Bogota-R-Users-Group/)
  * Cali: [Cali R Users Group](https://www.meetup.com/R-Users-Group-Cali/)

### Costa Rica `r get_btn()`

  * Quesada: [San Carlos R Users Group](https://www.meetup.com/San-Carlos-R-User-Group/)
  
  * Heredia: [Heredia R Users Group meetup](https://www.meetup.com/es/Heredia-R-User-Group/); [\@Heredia_rug](https://twitter.com/Heredia_rug)

### Ecuador  `r get_btn()`  

  * Quito: [R Users Group - Ecuador](http://www.rusersgroup.com/); [\@rusersgroup](https://twitter.com/rusersgroup)

### Nicaragua `r get_btn()`

  * Managua: [Usuarios R Nicaragua](https://www.facebook.com/groups/usuariosrnicaragua/)
  
### Panama `r get_btn()`

  * Panamá: [Panama R User's Group](https://www.meetup.com/Panama-R-Users-Group/)

### Peru`r get_btn()`

  * Perú: [Peru R User's Group - Peruvian Association of R Programming](https://www.facebook.com/rgroupperu/)
