---
knit: "bookdown::preview_chapter"
---

# Virtual Events

The format for listing a Virtual R event is

  * Date: [event name & link](http://www.example.com). [\@twitter_handle](https://twitter.com/twitter_handle).

## 2022 `r get_btn()` {-}

### April

  * April 27-29: [2022 Appsilon Shiny Conference](https://appsilon.com/2022-appsilon-shiny-conference/).
  * April 15-17: [Why R? Turkey 2022](https://whyr.pl/2022/turkey/en/). [\@WhyRTurkey](https://twitter.com/WhyRTurkey)
  
### March

  * March 14-15: [Workshop on Parallel Computing in R](https://warwick.ac.uk/research/rtp/sc/sulis/events/parallelr/).

## 2021 `r get_btn()` {-}

### December

  * December 10: [Why R? 2021](http://2021.whyr.pl/). [\@whyRconf](https://twitter.com/whyrconf)

### November

  * November 24-26: [The Use of R in Official Statistics](https://r-project.ro/conference2021.html)
  * November 19: [Korea R Conference](https://use-r.kr/)
  * November 10-12: [LatinR 2021](https://latin-r.com/en). [\@latinr_conf](https://twitter.com/latinr_conf)
  * November 8-13: [Coda BR 2021](https://escoladedados.org/coda2021/).
  * November 1-5 & 8-10: [NHS-R Community Conference 2021](https://nhsrcommunity.com/nhs-r-community-conference-2021/). [\@NHSrCommunity](https://twitter.com/NHSrCommunity)

### September

  * September 29-30: [noRth 2021](https://rnorthconference.github.io/).
  * September 6-10: [Earl 20201](https://info.mango-solutions.com/earl-2021).

### August

   * August 4-6: [BioC2021](https://bioc2021.bioconductor.org/).
   * August 24-27: [R Medicine](https://events.linuxfoundation.org/r-medicine/). [\@r_medicine](https://twitter.com/r_medicine).

### July

  * July 6-9: [useR 20201](https://user2021.r-project.org/).

### June

  * June 4-5: [CascadiaRConf](https://cascadiarconf.com/). [\@cascadiarconf](https://twitter.com/cascadiarconf)
  * June 17: [R Lille Meetup](https://www.meetup.com/R-Lille/events/277902715/). [\@rlille_rug](https://twitter.com/rlille_rug)
  
### April

  * April 15: [R Lille Meetup](https://www.meetup.com/R-Lille/events/277031496/). [\@rlille_rug](https://twitter.com/rlille_rug).
  * April 16-18: [WhyR? Turkey 2021](http://whyr.pl/2021/turkey/)
  * April 29: [R Lille Meetup](https://www.meetup.com/R-Lille/events/277132394/). [\@rlille_rug](https://twitter.com/rlille_rug).

### January
  
  * January 21: [RStudio Global](https://rstudio.com/conference/).
  * January: [Evidence Synthesis & Meta-Analysis in R](https://www.eshackathon.org/events/2021-01-ESMAR.html). [\@eshackathon](https://twitter.com/eshackathon)

## 2020 `r get_btn()` {-}

### December

  * December 2-4: [The R Conference | Government & Public Sector](https://rstats.ai/gov/). [#rstatsdc](https://twitter.com/search?q=%23rstatsdc&src=typed_query).

### November

  * November 14: [SatRday Columbus](https://columbus2020.satrdays.org/). [#satRdayColumbus](https://twitter.com/search?q=%23satRdayColumbus&src=typed_query).

### October

  * October 12-16: [R in Pharma](https://rinpharma.com/).
  * October 7-9: [LatinR 2020](https://github.com/LatinR/presentaciones-LatinR2020). [\@latinr_conf](https://twitter.com/latinr_conf)

## September

  * September 24-27: [Why R](https://2020.whyr.pl/)

### August
  
  * August 12-15: [New York R Conference](https://rstats.ai/nyr/)
  * August 27-30: [R in Medicine](https://events.linuxfoundation.org/r-medicine/).

### July

  * July 7-10: [useR! 2020](https://user2020.r-project.org/). [\@useR2020stl](https://twitter.com/useR2020stl).
  * July 7-10: [useR! 2020 European Hub](https://user2020muc.r-project.org/). [\@useR2020muc](https://twitter.com/useR2020muc).
  * July 14-15: [noRth 2020](https://rnorthconference.github.io/).
  * July 23: [Newcastle Data Science Meet-up](https://www.meetup.com/Newcastle-Upon-Tyne-Data-Science-Meetup/events/271494400/).

### June

  * June 17-22: [eRum 2020](http://2020.erum.io/). [\@erum2020_conf](https://twitter.com/erum2020_conf).
  * June 23: [LondonR](https://mango-solutions.zoom.us/meeting/register/tJAtfuGsqjgiHtCTMIp4hgGHQTvfK8kD1kiU).
  * June 28: [BristolR](https://www.meetup.com/Bristol-R-User-Group/events/271309225/).

### May

  * May 30: [SatRday Chicago](https://chicago2020.satrdays.org).
